name: Security Scan

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run OSV Scanner
      uses: google/osv-scanner-action/osv-scanner-action@v1
      with:
        args: '--recursive . --format sarif --output sarif-results.sarif'
    
    - name: Upload SARIF report to Security Dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif-results.sarif

    # Optional: Add notification step (Slack, Email, etc.)
    # - name: Send Security Alert
    #   uses: ... # Add your notification action here
