name: Semgrep Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  semgrep-analysis:
    runs-on: ubuntu-latest
    container: returntocorp/semgrep

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Semgrep analysis
      run: |
        semgrep --config=p/java --sarif --output=semgrep-results.sarif

    - name: Upload SARIF report to security dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-results.sarif
